In [ ]:
# Nueral networks from scratch book.
# Introduction to neural networks

# What are neural networks?
# Neural netwworks are the foundational component of building deep learning algorithms. 
# Neural networks are fundamental building block units for neural networks.
# Artificial neurons are used to construct layers (Which can be represented as matrices)
# Deep learning is the concept of having several hidden layers. The hidden layers are the ones
# that the neural network controls. Most neural networks in use are a form of deep learning

# Artificial Inelligence -> Machine learning -> Neural networks -> Deep learning

# Supervised learning is learning with pre-established labels. Unsupervised learning is learning 
# from data without explicit labels. 

# A measure about the information of we are trying to predict is called the feature. A group of features
# is called the feature set (which is represented as a vector). The values of a feature set can be regarded
# as a sample. Samples are fed into neural network models to train them to fit desired output
# from these inputs and predict based on them at inference time. 

# Labels are teh outputs that occured during each sample. so each sample is labeled with the actual outcome of the
# sample based on the feature set. Labels can also be referred to as targets or ground truths.

# Reinforcment learning is a form of unsupervised learning
# Generative learning is also a form of unsupervised learning
# So essentially, I'm specializing in forms of unsupervised learning. 
# Neural networks were conceived in the 1940s but figuring out how to train them
# was a big issue till the invention of backpropagation in the 1960s by Geoff Hinton et al.
# Neural networks became an area of attention when they started winning competitions in 2010


# What is a neural network?
# Artificial neural networks are inspired by the organic brain which has its own
# form of neural networks. It is not a perfect comparison, but in the brain there are 
# neurons, activations adn a lot of interconnectivity (with layers?)

# Artificial neural networks are syntactically similar to biological neural networks.


In [1]:
# A single neuron itself is useless(can be used in a linear regression problem where the data can be fit into a straingt line)
# But connecting multiple neurons together can build powerful capabilities. 

"""
Input layer 10
H1 = 16
H2 = 16
H3 = 16
O = 2

    M       V 
L1(10*16) + 16 = 160 + 16
L2(16*16) + 16 = 256 + 16
L3(16*16) + 16 = 256 + 16
L4(16*2) + 2 = 32 + 2
		
		704 + 50 = 754 total params


In the neural network above we have 4 affine matrices and 4 vectors
The vector transformations can be seen as mini-functions that are combined
To build the complex function. The output vectors of each of the transformation can 
Be seen as some sort of intermediary vector representation of the data.
"""

# We understand 'how' neural networks work but we dont undertand 'why' they work. I feel Its one of thos big mathematical mysteries.
# Dense layers/ Linear layere the most common type of neural network layer, where every neuron in a layer is fully connected to all the
# neurons of the previous layer and the next layer. This means that the output of a neuron in a particular layer becomes the input to a neural 
# network in the next layer. Each neuron has a weight connected to it, which are the trainable parameters. 

# Once al input flow through the connected weights, they are summed up and added to the bias term, then an activation function is applied on the result
# to apply non linearity to the output of the neuron. 

# The purpose of the bias is to offset the input positively or negatively
# The concept of weights and biases can be thought of as knobs that we can tune to fit our model to the data.
# In mordern neural networks, we can have thousands, millions or even billions of parameters. 

# The parameters are tuned by the optimizer durin training. 

# Weights change the magnitude and direction of the neuron while biases shift theh value eiter up or down along the output plane. 
# Weigtts and bias help affect the output neuron but they do so in slightly different ways.

# Scale and normalize your data (preprocessing before passing it into the network)

# For classification, you can use one nueron to represent each output class. For binary classification,
# you could implement it in a way where there is only a single output nueron, but you can use some heuristics to 
# determine the output. 

# What makes nueral networks look challenging is the math involved adn how scary it can sometimes look.

# A typical neural network has thousands of 'adjustable' parameters (weights and biases).
# In this wasy neural networks work as vast functions with an enormous amount of parameters. 
# Finding the right comdination of inputs and outputs to solve a specific problem is the why we train our model with optimizers
# One major issue in supervised machine learning is the problem of overfitting. When the model simply trains to fit in the training
# data then the model does not really 'understand' anything, it is just trying to cram/memorize the results for a given input. 

# Thus we use in-sample data to train our model, and outsample data to test it. 
# The idea of our model trying to learn underlying distributions about our data is known as generalization. 

# We calculate how wrong our neural networks are through an algorithm called the loss function. and we slowly 
# adjust our parameters based on the derivative of the loss function over many iterations till the loss function is minimized. 
# This can be rephrased as an optimization problem, this is why we use optimization alogrithms to train our neural network
# because we are trying to optimize our parameters to have the lowest possible loss function. 
# But the goal is to enable the network generalize on previously unseen data.




'\nInput layer 10\nH1 = 16\nH2 = 16\nH3 = 16\nO = 2\n\n    M       V \nL1(10*16) + 16 = 160 + 16\nL2(16*16) + 16 = 256 + 16\nL3(16*16) + 16 = 256 + 16\nL4(16*2) + 2 = 32 + 2\n\t\t\n\t\t704 + 50 = 754 total params\n\n\nIn the neural network above we have 4 affine matrices and 4 vectors\nThe vector transformations can be seen as mini-functions that are combined\nTo build the complex function. The output vectors of each of the transformation can \nBe seen as some sort of intermediary vector representation of the data.\n'

In [4]:
# Coding a simple neuron

import numpy as np
import matplotlib.pyplot as plt


# A single neuron
# This hypothetical neuronn has 3 inputs
inputs = [1, 2, 3, 2.5]

# Our network will have weights initialized randomly (should they really be random)
# and it should have a bias starting from 0. 

# Each input needs a weight associated with it. 
# Inputs are the data we pass into the network to get the desired output. 
# The values for the weights and biases are what get trained by the neural network.
# And these are the values that make the model actually work (or not work).

# We will simulate weights for now assigining a single weight to each input
weights = [0.2, 0.8, -0.5, 1.0]
# For a single neuron only 1 bias value is needed. ie for every set of inputs and weights, there is a single bias value for their dot product.
# For every set of neuron outputs there is an equivalent set of bias values.
bias = 2


# The product of each input and its equivalent weight and the result of that operation added to the bias gives you the output of that 
# neuron. 

output  = (inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3]) + bias

# The output of this simulated neuron is :
print(output)

4.8


In [5]:
# A layer of Neurons
# Neural networks usually have layers that consist of more than one neuron output. 
# Layers are simply a group of neurons stacked on top of each other. 
# Each layer takes a single set of inputs for all the neurons in that layer.
# The layers output is equivalent to the number of neurons in that layer. 

# Each neuron in a layer has its own bias term
# Lets experiment with a neural network with 4 inputs and 3 neurons (i.e. 3 outputs for that layer)

weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias2 = 3
bias3 = 0.5

output1  = (inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3]) + bias
output2  = (inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3]) + bias2
output3  = (inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3]) + bias3


outputs = [
    output, 
    output2,
    output3,
]

outputs

[4.8, 1.21, 2.385]

In [7]:
# In the example above, we have 3 sets of weights adn 3 biases which match to the number 
# of output neurons in our layer. Each neuron is connected to the same set of inputs. 
# The difference is in the seperate weights and biases. 

# This is called a fully connected neural network. where every neuron in a current layer
# is connected to every output of the previous layer.

# Fully connected neural networks are popular but they are not a requiremetn
all_weights = [weights, weights2, weights3]
biases = [bias, bias2, bias3]

layer_outputs = []
# This will loop to the number of outputs in the layer
for neuron_weights, bias in zip(all_weights, biases):
    output = 0
    # This loops to the number of inputs in the layer
    for input, weight in zip(inputs, neuron_weights):
        output += input * weight
    output += bias
    layer_outputs.append(output)
    
print(layer_outputs)

[4.8, 1.21, 2.385]


In [8]:
# zip() allows us to loop thruogh two iterables of the same size simultaneously.
# We can tell we have 3 neurons because we have 3 different sets of weights and biases. 

# Now lets start thinking of these objects in a more efficient way: Tenors

In [ ]:
# Tensors, Arrays and Vectors
# Tensors are closely-related to arrays. 
# A tenor is an object similar to an array, or matrix. 

In [9]:
# A single list {1 sample}
l = [1, 5, 6, 2]

In [10]:
# A list of list, can be seen as a table of data, or a matrix
lol = [[1, 5, 6, 2], 
       [3, 2, 1, 3]]

In [11]:
# This is a list of lists of lists, it can also be called a tensor.
# This can also be viewed as a representation of an image of size (3, 2, 4).
# 3 Channels for RGB, and 2 rows by 4 columns.

lolol = [[[1, 5, 6, 2], 
       [3, 2, 1, 3]],
        
       [[5, 2, 1, 2], 
       [6, 4, 8, 4]],
       
       [[2, 8, 5, 3], 
       [1, 1, 9, 4]],
        ]

In [13]:
an_imbalanced_list_of_lists = [[4, 2, 3],
                               [5, 1]]
# This is not a 'homogeneous' list and can not be used in machine learning.
# A list of lists is homogenous if all the dimensions of the lists within it are the same.
# The first dimension is the number of sublists the second dimension is the number of items within each sublist. 
# (4,3) = (rows, columns)


In [15]:
# Matrix, a martix is a rectagular array, it has 2 dimensions, rows and colums.
# It can also be referred to as a 2d array. 
# We can have infinitely dimensional matrices

list_matrix_arra = [[4, 2],  # this can be viewed as a list of items in a table, with two columns per item
                    [5, 1], 
                    [8, 2]]

In [18]:
# 3D matrices, commonly used to represent images

lolol = [[[1, 5, 6, 2], 
       [3, 2, 1, 3]],
        
       [[5, 2, 1, 2], 
       [6, 4, 8, 4]],
       
       [[2, 8, 5, 3], 
       [1, 1, 9, 4]],
        ]

In [20]:
# lets analyze the 3d matrix
lolol[0], lolol[1], lolol[2]

([[1, 5, 6, 2], [3, 2, 1, 3]],
 [[5, 2, 1, 2], [6, 4, 8, 4]],
 [[2, 8, 5, 3], [1, 1, 9, 4]])

In [ ]:
# The shape of the lolol matrix is (3, 2, 4)

In [21]:
# So that brings us back to the question, what is a tensor. 
# Pages of computer science have been written on the debate of tensors vs arrays.

# A tensor object is an object that can be represented by an array.
# We will tenssors as arrays in the context of deep leanring
# Tensors are the foundational representations we use to build concepts in deep learning

In [22]:
# Tensors are not just arrays, but they are represented as just arrays in code
# An array is an ordered homogenous container for working with numbers.
# Arrays are the main datastructure of the numpy package. 
# A linear array is also called a 1-dimensional array which can also be refered to as a vector.
# Arrays can be used to build representations of matrices in code. by simply
# creating a 2-dimensional array. 
# The items in the matrix can be accessed by using a tuple of indices as the key

# A vector in mathematics is what we call a list in python, or a 1-dimensional array in numpy
# We can then build matrices as an array of arrays.
# We also look at the vectors algebraically as a set of numbers within a bracket. 

# For the context of deep learnign we do not look at vectors from the perspective of 
# physicists who look at vectors as an array in space characterized by magnitude and direction.



In [23]:
# Dot product and vector additions
sample = np.array([[1, 2, 3], # These can be viewed as the neuron outputs for each input
          [4, 5, 6]])

adding = np.array([3, 2, 1]) # This can be seen as the bias

sample + adding

array([[4, 4, 4],
       [7, 7, 7]])

In [24]:
# How do vectors multiply?
# Multiplication one of the most important operations we will perform on a vector. 
# We can achieve the same implementation in python by multiplying each index against the other and summing 
# the results in two equally sized lists, this is known as the dot product. 
# Because of the number of variable interconnections made we can model complex non linear relationships
# with activation functions, which allow us to compound the results of a set of operations above each other 
# and achieve non linearity in or function. 

# When multiplying vectors you can either do a dot product or a cross product.
# A cross product will produce a vector, while a dot product will produce a scalar value (single value/number)

# vec_a . vec_b = sum[i=0, n](vec_a[i]*vec_b[i])

# where n is the number of items in the vector, for dot product to work, both vectors have to be of the same size


In [25]:
a = [1, 2, 3]
b = [2, 3, 4]

dot_product = a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
dot_product

20

In [26]:
# In the context of deep learning, we can call a the input and b the weights
# suddenly it becomes apparent the the neural network output operation was simply 
# a dot product operation. 

# plain python does not allow us to perform dot products natively,
# So we would be using the numpy package. 
# Numpy also allows us perform other operations that are very helpful to 
# deep learinng such as vector addition.
# This the element-wise addition of vectors, although the two vectors must be
# of the same size. 
# vec_a + vec_b  = [vec_a[0] + vec_b[1], vec_a[2] + vec_b[2], ...., vec_a[n]+vec_b[n]]


In [27]:
# Building a single neuron with numpy
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2

output = np.dot(inputs, weights) + bias
output

4.8

In [28]:
# Builing a Layer of neurons with numpy
# We would be calculating the output of a layer with 3 neurons.
# This means that the weights should be a matrix. This is becuase as we can see 
# in the cell above, a single neuron is an array/vector. So given our knowledge of 
# linear algebra, we can say that a set of vectos sis a matrix, therefore a set of
# neurons (which are vectors) is a matrix. To sum it up a layer is a matrix, keep that
# mental image in mind for future reference. 


# Numpy treats matrices as a list of vectors. It perform the dot product of 
# each vector individually one after the other. 
# returning a list of the result of the dot product for each vector. 

# We would simply add the biases directly as they are matrices of the same shape with the output of the dot product 
# of the weight matrix and the input. So we would simply add the correspoding biases to each of them.

inputs = [1.0, 2.0, 3.0, 2.5]
weight_matrix = [[0.2, 0.8, -0.5, 1],
                 [0.5, -0.91, 0.26, -0.5],
                 [-0.26, -0.27, 0.17, 0.87]]

biases = [2.0, 3.0, 0.5]


In [32]:
np.dot(weight_matrix, inputs) + biases

array([4.8  , 1.21 , 2.385])

In [33]:
# The proces of matrix vector multiplication and then addition with another vector
# is the simplest and common way of represiting input.weights + bias. 

In [34]:
# Working with a batch of data.
# So far we have only been working on one sample observation.
# But in deep learning we usually deal with large sets of samples (datasets).
# It would be more efficient if we could perform these matrix operations simultaneously
# on a whole set of data in one pass. 


# The challenges in this occur when we are tryrin to perform a matrix operation on the data
# Becuase of the way matrix is formatted, which is (row, col) We would not be able to 
# perform the matrix operations directly as we have previously done. This is becauese the 
# input shape of the first matrixe in the matrix multiplication must be the same with the output of 
# second matrix in the matrix multiplication. Now because our shape has changed to have (num_instances, num_featurs)
# from (num_featurs, ) We would not be able to perform matrix multiplication directly the way we did previously.
# because the shapes simply don't match anymore. 
# But given the benefits of working with batches of data, such as efficiency and parallilization. 
# Also, trianing with batches help in achieving generalization faster and better. Since you would not be 
# making adjustments based on a single input, but over ta batch of inputs.


# At this point, we are conceptually thinking of a matrix of inputs and a matrix of weights.
# In this case, we would need to think of something a bit more complex than a dot product, we would have to think of matrix products,


In [36]:
# Matrix product
# A matrix product is an operation of two matrices. 

# Matrix product requires one set of vectors to be arranged horizontally and the other vertically
# But in our case both inputs and weights are aligned horizontally. 

# This size of the second dimension of the first matrix must align with the size of the dimension of the first dimension on the 
# second matrix. 

# Column vectors are vectors of a column of a matrix
# Row vectors are vectors of a row of a matrix


In [38]:
# Transposition of the matrix product. 
# a.bT <- matrix product of a and b transpose


# Transposition is the rotation of a matrix along the diagonal axis. 
# This happens in such a way that the rows become columns and the columns become rows.

# A row vector is a vector where its first dimension equals 1 i.e (1, 8)
# this represents one row and 8 columns. 

#  A column vector is a matrix with the second dimension equal to 1 i.e (8, 1)
row_vector = np.array([[1, 2, 3]])
row_vector, row_vector.shape

(array([[1, 2, 3]]), (1, 3))

In [43]:
row_vector.T

array([[1],
       [2],
       [3]])

In [39]:
column_vector = np.array([[1], [2], [3]])
column_vector, column_vector.shape

(array([[1],
        [2],
        [3]]),
 (3, 1))

In [42]:
column_vector.T

array([[1, 2, 3]])

In [48]:
np.dot(row_vector, column_vector)

array([[14]])

In [47]:
np.dot(column_vector, row_vector)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [50]:
# A layer fo Neurons with a batch of data.
# Looking back at the inputs and weights, we need to perform transposition on the second argument in the matrix multiplication.
# The second arguement in our case will be the weight matrix. It will turn the row vector of 
# neurons into column vectors. 

# We were able to perform this operation without any issues before because our weights were in a matrix
# while our input was in a vector (a single sample).


# We plan to represent the samples as a set of row vectors and then the weights as a set of column vectors. 

inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]


biases = [2.0, 3.0, 0.5]

output = np.dot(inputs, np.array(weights).T) + biases
output

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [ ]:
# The reason we transpose the weights rather than the inputs is because we 
# want our outputs to be sample related and no neuron related as we pass it further through the 
# network, as the next layer will be expecting a batch of inputs which would be expected to be a stack of 
# row vectors. 


# This is why we pass in a list of samples even if there is only one sample, and it returns a list of predictions
# even though there is only a single prediction. 