In [1]:
# walking through pytorch documentation of tensors
# Tensors are specialized datastructures that are similar to arrays and matrices

# Tensors are used to encode inputs and outputs of model, as well as the models parameters

# Tensors are very similar to nd array, except that Tensors run on the GPU or other hardware acdelerators
# Tensors are also optimized for automatic differentiation

import torch
import numpy as np


In [4]:
data = [[1, 2], [3, 4]]
t = torch.Tensor(data) # initializing a 2 dimensional tensor from an existing 2 dimensional array
t

tensor([[1., 2.],
        [3., 4.]])

In [3]:
# pytorch tensors can also be created from numpy arrays
np_array = np.array(data)
np_array

array([[1, 2],
       [3, 4]])

In [5]:
tnp_array = torch.from_numpy(np_array)
tnp_array

tensor([[1, 2],
        [3, 4]])

In [8]:
# create tensors with different values but same structures as other tensors
t_ones = torch.ones_like(tnp_array)
t_ones

tensor([[1, 1],
        [1, 1]])

In [10]:
t_rand = torch.rand_like(tnp_array, dtype=torch.float32)
t_rand

tensor([[0.6534, 0.0337],
        [0.0182, 0.0250]])

In [11]:
# create tensors by only specifying the shape
shape = (3, 2)

tensor_ones = torch.ones(shape)
tensor_ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [12]:
tensor_zeros = torch.zeros(shape)
tensor_zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [13]:
tensor_rand = torch.rand(shape)
tensor_rand

tensor([[0.2884, 0.1596],
        [0.5068, 0.3151],
        [0.8002, 0.2442]])

In [14]:
# attributes of a tensor
tensor_rand.shape

torch.Size([3, 2])

In [15]:
tensor_rand.dtype

torch.float32

In [16]:
tensor_rand.device

device(type='cpu')

In [17]:
mpu_tensor_rand  = tensor_rand.to("mps")

In [18]:
mpu_tensor_rand

/Users/kosisochukwuasuzu/Developer/machine_learning/dive-into-deep-learning/.venv/lib/python3.10/site-packages/torch/_tensor_str.py:103: UserWarning: The operator 'aten::bitwise_and.Tensor_out' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))


tensor([[0.2884, 0.1596],
        [0.5068, 0.3151],
        [0.8002, 0.2442]], device='mps:0')

In [19]:
tensor_rand

tensor([[0.2884, 0.1596],
        [0.5068, 0.3151],
        [0.8002, 0.2442]])

In [20]:
# Important attributes of a tensor
# 1) Shape
# 2) Data type
# 3) Device

# most likely if you run into issues its one of these 3



In [22]:
# operations of a tensor, they can be run on ether the CPU or GPU, based on the backend device you specify
tensor = torch.rand((4, 4))
tensor

tensor([[0.5648, 0.0615, 0.3294, 0.1197],
        [0.2613, 0.3797, 0.8356, 0.9672],
        [0.5478, 0.5639, 0.9104, 0.1581],
        [0.4095, 0.3286, 0.4241, 0.5265]])

In [28]:
# first row
tensor[0]

tensor([0.5648, 0.0615, 0.3294, 0.1197])

In [29]:
# first column
tensor[:, 0]

tensor([0.5648, 0.2613, 0.5478, 0.4095])

In [32]:
# last column
tensor[:, -1]

tensor([0.1197, 0.9672, 0.1581, 0.5265])

In [38]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t1

tensor([[0.5648, 0.0615, 0.3294, 0.1197, 0.5648, 0.0615, 0.3294, 0.1197, 0.5648,
         0.0615, 0.3294, 0.1197],
        [0.2613, 0.3797, 0.8356, 0.9672, 0.2613, 0.3797, 0.8356, 0.9672, 0.2613,
         0.3797, 0.8356, 0.9672],
        [0.5478, 0.5639, 0.9104, 0.1581, 0.5478, 0.5639, 0.9104, 0.1581, 0.5478,
         0.5639, 0.9104, 0.1581],
        [0.4095, 0.3286, 0.4241, 0.5265, 0.4095, 0.3286, 0.4241, 0.5265, 0.4095,
         0.3286, 0.4241, 0.5265]])

In [39]:
# Matrix opertions
y1 = tensor @ tensor.T
y1

tensor([[0.4456, 0.5619, 0.6628, 0.4542],
        [0.5619, 1.8460, 1.2708, 1.0953],
        [0.6628, 1.2708, 1.4718, 0.8789],
        [0.4542, 1.0953, 0.8789, 0.7327]])

In [42]:
y2 = tensor.matmul(tensor.T)
y2

tensor([[0.4456, 0.5619, 0.6628, 0.4542],
        [0.5619, 1.8460, 1.2708, 1.0953],
        [0.6628, 1.2708, 1.4718, 0.8789],
        [0.4542, 1.0953, 0.8789, 0.7327]])

In [43]:
y3 = torch.rand_like(y2)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[0.4456, 0.5619, 0.6628, 0.4542],
        [0.5619, 1.8460, 1.2708, 1.0953],
        [0.6628, 1.2708, 1.4718, 0.8789],
        [0.4542, 1.0953, 0.8789, 0.7327]])

In [45]:
# Element wise multiplication
z1 = tensor * tensor
z1

tensor([[0.3190, 0.0038, 0.1085, 0.0143],
        [0.0683, 0.1441, 0.6982, 0.9354],
        [0.3001, 0.3180, 0.8288, 0.0250],
        [0.1677, 0.1080, 0.1798, 0.2772]])

In [46]:
z2 = tensor.mul(tensor)
z2

tensor([[0.3190, 0.0038, 0.1085, 0.0143],
        [0.0683, 0.1441, 0.6982, 0.9354],
        [0.3001, 0.3180, 0.8288, 0.0250],
        [0.1677, 0.1080, 0.1798, 0.2772]])

In [47]:
z3 = torch.rand_like(z2)
torch.mul(tensor, tensor, out=z3)
z3

tensor([[0.3190, 0.0038, 0.1085, 0.0143],
        [0.0683, 0.1441, 0.6982, 0.9354],
        [0.3001, 0.3180, 0.8288, 0.0250],
        [0.1677, 0.1080, 0.1798, 0.2772]])

In [48]:
agg = tensor.sum()
agg

tensor(7.3879)

In [50]:
agg.item(), type(agg.item())

(7.387904167175293, float)

In [51]:
# inplace operations are followed witn an underscore after the name of the opertion
tensor

tensor([[0.5648, 0.0615, 0.3294, 0.1197],
        [0.2613, 0.3797, 0.8356, 0.9672],
        [0.5478, 0.5639, 0.9104, 0.1581],
        [0.4095, 0.3286, 0.4241, 0.5265]])

In [52]:
tensor.add_(5)

tensor([[5.5648, 5.0615, 5.3294, 5.1197],
        [5.2613, 5.3797, 5.8356, 5.9672],
        [5.5478, 5.5639, 5.9104, 5.1581],
        [5.4095, 5.3286, 5.4241, 5.5265]])

In [53]:
tensor

tensor([[5.5648, 5.0615, 5.3294, 5.1197],
        [5.2613, 5.3797, 5.8356, 5.9672],
        [5.5478, 5.5639, 5.9104, 5.1581],
        [5.4095, 5.3286, 5.4241, 5.5265]])

In [56]:
# Tensors on th CPU and numpy arrays can share the same memery location
t = torch.ones((2, 2))
t

tensor([[1., 1.],
        [1., 1.]])

In [61]:
np_t = t.numpy()
np_t

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [62]:
# The operations on the numpy array dont affect the tensor, but the operations on the tensor affect the numpy array
t.add_(5)
np_t

array([[6., 6.],
       [6., 6.]], dtype=float32)

In [66]:
# np array to tensor
np_a = np.array([[1, 2], [3, 4]])
t2 = torch.from_numpy(np_a)
t2

tensor([[1, 2],
        [3, 4]])

In [67]:
np.add(np_a, 5, out=np_a)
t2, np_a

(tensor([[6, 7],
         [8, 9]]),
 array([[6, 7],
        [8, 9]]))