In [2]:
# learning the preliminaries needed for deep learning.
# First we will cover reading and processing of data.

# n-dimensional array is called a tensor. the tensor class supports 
# automatic differentiation. Second, it leverages GPUs to accelerate 
# numerical computation, whereas NumPy only runs on CPUs. 
# These properties make neural networks both easy to code and fast to run.
import torch
import jax
from jax import numpy as jnp
import tensorflow as tf


A one dimentional tensor is known as vector, a 2 dimentional tensor is known as a matrix, while a tensor with dimensions greater than 2 is known as the dimentional size order tensor.

In [3]:
# using pytorch

torch_x = torch.arange(12, dtype=torch.float32)
torch_x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

The one from pytorch is refered to as a tenso class

In [10]:
# using mxnet
jax_x = jnp.arange(12, dtype=jnp.float32)
jax_x

Array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],      dtype=float32)

The one from jax is regarded as an array class

In [11]:
# using tensorflow
tf_x = tf.range(12, dtype=tf.float32)
tf_x

Metal device set to: Apple M1 Pro

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB



<tf.Tensor: shape=(12,), dtype=float32, numpy=
array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
      dtype=float32)>

The class of the result of tf_x is also an array, similar to that of jax, but different from that of pytorch, could it be because they are both developed by google  lol. Wait, it's in a parent class callled tf.Tensor, so its a bit of both, hmm

In [12]:
# getting the number of items in a tensor in pytorch
torch_x.numel()

12

In [13]:
# getting the number of items in an array in jax
jax_x.size

12

In [15]:
# getting the number of items in a tf.Tensor in tensorflow
tf.size(tf_x)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [16]:
# we use the .shape attribute in all the packages to get the shape of the tensor 
jax_x.shape

(12,)

In [18]:
# reshaping all the vectors into matrices 
jax_x = jax_x.reshape(3, 4)
tf_x = tf.reshape(tf_x, (3, 4))
torch_x = torch_x.reshape(3, 4)

print(jax_x)
print(torch_x)
print(tf_x)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tf.Tensor(
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]], shape=(3, 4), dtype=float32)


In [20]:
tf.zeros((2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [23]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [22]:
jnp.zeros((2, 3, 4))

Array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)

In [25]:
tf.ones((2, 3, 4), dtype=tf.int32)

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)>

In [26]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [27]:
jnp.ones((2, 3, 4))

Array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

generating values of gaussian distribution with mean of 0 and standard deviation of 1

In [30]:
torch.randn((2, 3, 4))

tensor([[[-0.6098, -1.1948, -0.4374,  0.7247],
         [ 0.4508, -1.0023,  1.4691,  0.8865],
         [ 0.7082,  0.2902, -1.6812, -0.9743]],

        [[ 0.5307, -1.0626, -0.2514,  2.1197],
         [-0.3099,  0.7009, -0.0970,  0.2478],
         [ 0.7719, -0.9232,  1.1381, -0.6216]]])

In [31]:
jax.random.normal(jax.random.PRNGKey(0), (3, 4))

Array([[ 1.1901639 , -1.0996888 ,  0.44367844,  0.5984697 ],
       [-0.39189556,  0.69261974,  0.46018356, -2.068578  ],
       [-0.21438177, -0.9898306 , -0.6789304 ,  0.27362573]],      dtype=float32)

In [32]:
tf.random.normal(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-3.4537306e-04, -2.5005600e-01, -5.2125174e-01, -3.9218172e-01],
       [ 3.9020357e-01, -1.5002146e+00,  8.0105311e-01,  5.2865237e-01],
       [-3.9408860e-01, -1.5604352e+00,  1.9296621e-01, -3.3896801e-01]],
      dtype=float32)>

In [33]:
# constructing tensors from exact values in torch
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]], dtype=torch.float64)

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]], dtype=torch.float64)

In [35]:
# constructing tensors from exact values in jax
jnp.array(object=[[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]], dtype=jnp.float64)

/var/folders/8g/l0wz5p3d6175vd4ztcxpqfw40000gn/T/ipykernel_8273/1068862704.py:2: UserWarning: Explicitly requested dtype <class 'jax.numpy.float64'> requested in array is not available, and will be truncated to dtype float32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/google/jax#current-gotchas for more.
  jnp.array(object=[[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]], dtype=jnp.float64)


Array([[2., 1., 4., 3.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.]], dtype=float32)

In [36]:
# constructing tensors from exact values in tensorflow
tf.constant(value=[[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]], dtype=tf.float32)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[2., 1., 4., 3.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.]], dtype=float32)>

Accessing items within a tensor like

In [37]:
torch_x[-1]

tensor([ 8.,  9., 10., 11.])

In [38]:
torch_x[1:]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [42]:
jax_x[1]

Array([4., 5., 6., 7.], dtype=float32)

In [45]:
tf_x[0][1]

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

Jax arrays and tensor flows are immutable, to set them we must use special operations

In [46]:
jax_x.at[1,0].set(17)

Array([[ 0.,  1.,  2.,  3.],
       [17.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)

In [48]:
x_var = tf.Variable(tf_x)
x_var[1, 2].assign(9)
x_var

InvalidArgumentError: Cannot assign a device for operation ResourceStridedSliceAssign: Could not satisfy explicit device specification '/job:localhost/replica:0/task:0/device:GPU:0' because no supported kernel for GPU devices is available.
Colocation Debug Info:
Colocation group had the following types and supported devices: 
Root Member(assigned_device_name_index_=1 requested_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' assigned_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' resource_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
ResourceStridedSliceAssign: CPU 
_Arg: GPU CPU 

Colocation members, user-requested devices, and framework assigned devices, if any:
  ref (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  ResourceStridedSliceAssign (ResourceStridedSliceAssign) /job:localhost/replica:0/task:0/device:GPU:0

Op: ResourceStridedSliceAssign
Node attrs: T=DT_FLOAT, Index=DT_INT32, shrink_axis_mask=3, begin_mask=0, ellipsis_mask=0, new_axis_mask=0, end_mask=0
Registered kernels:
  device='XLA_CPU_JIT'; Index in [DT_INT32, DT_INT64]; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT16, 16005131165644881776, DT_UINT16, DT_COMPLEX128, DT_HALF, DT_UINT32, DT_UINT64]
  device='DEFAULT'; T in [DT_INT32]
  device='CPU'; T in [DT_UINT64]
  device='CPU'; T in [DT_INT64]
  device='CPU'; T in [DT_UINT32]
  device='CPU'; T in [DT_UINT16]
  device='CPU'; T in [DT_INT16]
  device='CPU'; T in [DT_UINT8]
  device='CPU'; T in [DT_INT8]
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_BOOL]
  device='CPU'; T in [DT_STRING]
  device='CPU'; T in [DT_RESOURCE]
  device='CPU'; T in [DT_VARIANT]
  device='CPU'; T in [DT_QINT8]
  device='CPU'; T in [DT_QUINT8]
  device='CPU'; T in [DT_QINT32]

	 [[{{node ResourceStridedSliceAssign}}]] [Op:ResourceStridedSliceAssign] name: strided_slice/_assign

In [49]:
tf_x

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

Tensorflows API is just unneccerily complex

In [51]:
torch_x[:2, :3] = 17
torch_x

tensor([[17., 17., 17.,  3.],
        [17., 17., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [53]:
jax_x.at[:2, :3].set(17)

Array([[17., 17., 17.,  3.],
       [17., 17., 17.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)

In [4]:
torch_x = torch_x.reshape(3, 4)

In [5]:
torch_x = torch.exp(torch_x)
torch_x

tensor([[1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01],
        [5.4598e+01, 1.4841e+02, 4.0343e+02, 1.0966e+03],
        [2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04]])

In [8]:
# to perform eleemnt wise tensor operation the elements must be of the same shape
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [11]:
x = torch.arange(12, dtype=torch.float32)
y = torch.arange(12, dtype=torch.float32)

x = x.reshape((3,4))
y = y.reshape((2,6))

In [14]:
y + x

RuntimeError: The size of tensor a (6) must match the size of tensor b (4) at non-singleton dimension 1

In [16]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [17]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [26]:
X > Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [27]:
X < Y

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [20]:
# sum of all the element values in a tesnor
X.sum()

tensor(66.)

In [19]:
Y.sum()

tensor(30.)

In [22]:
before = id(Y)
Y[:] = Y + X
id(Y) == before

True

In [23]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [25]:
# converting a pytorch tensor into a python scalar

a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

The tensor class is the main interface for storing and manipulating data in deep learning libraries. Tensors provide a variety of functionalities including construction routines; indexing and slicing; basic mathematics operations; broadcasting; memory-efficient assignment; and conversion to and from other Python objects

## Data Processing functions

In [28]:
import os


# create cv file for generated data
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')

In [30]:
import pandas as pd

# read dataframe from csv file
df  = pd.read_csv('../data/house_tiny.csv')
df.head()

NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000

In [31]:
df.columns

Index(['NumRooms', 'RoofType', 'Price'], dtype='object')

In [32]:
tf_tensor = torch.from_numpy(df)

TypeError: expected np.ndarray (got DataFrame)

In [34]:
inputs, targets = df.iloc[:, 0:2], df.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       NaN               0             1
1       2.0               0             1
2       4.0               1             0
3       NaN               0             1


In [35]:
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       3.0               0             1
1       2.0               0             1
2       4.0               1             0
3       3.0               0             1


In [36]:
X, y = torch.tensor(inputs.values), torch.tensor(targets.values)
X, y

(tensor([[3., 0., 1.],
         [2., 0., 1.],
         [4., 1., 0.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [39]:
import numpy as np
# can only load pick files
file = np.load("../data/house_tiny.csv", allow_pickle=True)
file

UnpicklingError: Failed to interpret file '../data/house_tiny.csv' as a pickle